;=======================================
; Mode 2 + Mode 0 COLDATA Gradient
; Channels: Red, Green, Blue
; Table Size: 119
; No. of Writes: 224
; 
; Generated by GradientTool
;=======================================

; Set up the HDMA gradient.
; Uses HDMA channels 3 and 4.
init:
	REP   #$20 ; 16-bit A

	; Set transfer modes.
	LDA   #$3202
	STA   $4330 ; Channel 3
	LDA   #$3200
	STA   $4340 ; Channel 4

	; Point to HDMA tables.
	LDA   #Gradient1_RedGreenTable
	STA   $4332
	LDA   #Gradient1_BlueTable
	STA   $4342

	SEP   #$20 ; 8-bit A

	; Store program bank to $43x4.
	PHK
	PLA
	STA   $4334 ; Channel 3
	STA   $4344 ; Channel 4

	; Enable channels 3 and 4.
	LDA.b #%00011000
	TSB   $6D9F

    LDA #$01
    STA $140B|!addr
    RTL
    
        RTL ; <-- Can also be RTL.

main:
	JSL freezetimer_main
	RTL

; --- HDMA Tables below this line ---
Gradient1_RedGreenTable:
db $01,$2E,$46
db $02,$2F,$47
db $01,$30,$47
db $02,$31,$48
db $84,$32,$49,$33,$49,$33,$4A,$34,$4A
db $02,$35,$4B
db $03,$36,$4C
db $03,$37,$4D
db $01,$38,$4D
db $03,$38,$4E
db $03,$39,$4F
db $01,$3A,$4F
db $03,$3A,$50
db $03,$3B,$51
db $01,$3C,$51
db $02,$3C,$52
db $02,$3D,$52
db $02,$3D,$53
db $01,$3E,$53
db $05,$3E,$54
db $05,$3E,$55
db $05,$3E,$56
db $05,$3E,$57
db $05,$3E,$58
db $05,$3E,$59
db $05,$3E,$5A
db $05,$3E,$5B
db $80,$3E,$5C
db $10,$3E,$5C
db $00

Gradient1_BlueTable:
db $01,$92
db $04,$93
db $03,$94
db $09,$95
db $09,$94
db $0D,$93
db $04,$92
db $0A,$93
db $09,$94
db $0A,$95
db $80,$96
db $18,$96
db $00
