;=======================================
; Mode 2 + Mode 0 COLDATA Gradient
; Channels: Red, Green, Blue
; Table Size: 87
; No. of Writes: 224
; 
; Generated by GradientTool
;=======================================

; Set up the HDMA gradient.
; Uses HDMA channels 3 and 4.
init:
	REP   #$20 ; 16-bit A

	; Set transfer modes.
	LDA   #$3202
	STA   $4330 ; Channel 3
	LDA   #$3200
	STA   $4340 ; Channel 4

	; Point to HDMA tables.
	LDA   #Gradient1_RedGreenTable
	STA   $4332
	LDA   #Gradient1_BlueTable
	STA   $4342

	SEP   #$20 ; 8-bit A

	; Store program bank to $43x4.
	PHK
	PLA
	STA   $4334 ; Channel 3
	STA   $4344 ; Channel 4

	; Enable channels 3 and 4.
	LDA.b #%00011000
	TSB   $6D9F

    LDA #$01
    STA $140B|!addr
    RTL

	RTL ; <-- Can also be RTL.

; --- HDMA Tables below this line ---
Gradient1_RedGreenTable:
db $70,$21,$41
db $02,$21,$42
db $04,$22,$42
db $02,$22,$43
db $01,$22,$44
db $02,$23,$45
db $8E,$23,$46,$23,$47,$24,$48,$24,$49,$25,$4A,$25,$4B,$26,$4C,$28,$4E,$2A,$4F,$2C,$51,$2E,$52,$30,$53,$32,$54,$33,$56
db $02,$34,$56
db $55,$35,$57
db $00

Gradient1_BlueTable:
db $6D,$82
db $03,$83
db $03,$84
db $03,$85
db $8B,$86,$87,$89,$8A,$8C,$8D,$8E,$90,$91,$92,$93
db $02,$94
db $02,$95
db $83,$96,$97,$98
db $04,$99
db $54,$9A
db $00
