!sa1	= 0
!dp	= $0000
!addr	= $0000
!bank	= $800000
!bank8	= $80
!700000	= $700000

if read1($00FFD5) == $23
	sa1rom
	!sa1	= 1
	!dp	= $3000
	!addr	= $6000
	!bank	= $000000
	!bank8	= $00
	!700000	= $41C000
endif

org $009D66
	LDA.l !700000+$8C,x
	PHA
	LDA #$00
	XBA
	LDA $04
	ASL
	TAY
	LDX.w SRAMIndex,y
	LDY.w #$000B
	STY $01
-
	LDA #$07
	STA $03
	LDA.l $41A000+192,x
--
	LSR
	BCC +
	INC $02
+
	DEC $03
	BPL --
	DEX
	DEC $01
	BPL -

	SEP #$10
	PLX
	PHB
	LDA #$7F
	PHA
	PLB
	LDA #$38	;Normal Exit count YXPCCCTT
	LDY $00
	autoclean JML Continue

SRAMIndex:	;static, copied from the tables generated by uberasm retry
dw $0000+$B,$0955+$B,$12AA+$B

org $05B734	;Adjust various stripes
db $29,$3C,$FC,$38
db $17,$34,$0E,$34,$20,$34
db $FC,$38,$FC,$38,$FC,$38,$FC,$38
org $05B758
db $29,$3C,$FC,$38
db $17,$34,$0E,$34,$20,$34
db $FC,$38,$FC,$38,$FC,$38,$FC,$38
org $05B77C
db $29,$3C,$FC,$38
db $17,$34,$0E,$34,$20,$34
db $FC,$38,$FC,$38,$FC,$38,$FC,$38

org $05B7FF
db $29,$3C,$FC,$38
db $17,$34,$0E,$34,$20,$34
db $FC,$38,$FC,$38,$FC,$38,$FC,$38
org $05B823
db $29,$3C,$FC,$38
db $17,$34,$0E,$34,$20,$34
db $FC,$38,$FC,$38,$FC,$38,$FC,$38
org $05B847
db $29,$3C,$FC,$38
db $17,$34,$0E,$34,$20,$34
db $FC,$38,$FC,$38,$FC,$38,$FC,$38

freedata
Continue:
	CPX.b #122	;Total Exit count
	BCC +
	LDA #$28	;Total Exit count YXPCCCTT	
+
	STA $837D-1,y
	STA $837D+1,y
	STA $837D+3,y
	TXA
	JSL $00974C|!bank
	STA $837D+2,y
	TXA
	JSL $00974C|!bank
	PHA
	TXA
	BNE +
	SEC
	LDA #$FC
+
	STA $837D-2,y
	PLA
	BNE +
	BCC +
	LDA #$FC
+
	STA $837D,y
	LDA #$FC
	STA $837D+4,y
.coin
	LDX $02
	BNE +
	LDA #$FC
	STA $837D+$6,y
	STA $837D+$8,y
	BRA .end
+
	LDA #$2E	;Coin tile
	STA $837D+$6,y
	LDA #$3C	;Coin YXPCCCTT
	STA $837D+$7,y
	LDA #$38	;Coin count YXPCCCTT
	CPX #67		;Total Coin count
	BCC +
	LDA #$28	;Total Coin count YXPCCCTT
+
	STA $837D+$9,y
	STA $837D+$B,y
	TXA
	JSL $00974C|!bank
	PHA
	TXA
	BNE +
	LDA #$FC
	STA $837D+$A,y
	DEY
	DEY
	BRA ++
+	
	STA $837D+$8,y
++
	PLA
.end
	STA $837D+$A,y
	PLB
	JML $009DA6|!bank
